######################################################################
# Automatically generated by qmake (3.0) Mon Dec 7 04:59:14 2020
######################################################################

TEMPLATE = app
TARGET = chatProg
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += ButtonWindow.h
SOURCES += ButtonWindow.cpp
